version: '3.8'

services:
  dagobah:
    image: jmcontreras20/dagobah:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "80:8080"
      - "443:8080"
    environment:
      - SPRING_DATASOURCE_URL=mongodb://mongo:password@mongo:27017/dagobah
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: dagobah
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-init:
    build: ./db
    depends_on:
      - mongo